### ISSUE TITLE
ScribblejrExt crashes when drawing text with a color code

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/ScribbleJunior#1]
It sounds like this should work:

    ScribblejrAddColor("c_red", #cc0000);
    -----
    var str = "The quick [c_red]brown fox[/c] jumped over the lazy dog";
    var jr = ScribblejrExt(str, fa_left, fa_middle, undefined, 1);
    jr.Draw(200, 250);

but instead it crashes with `Variable __ScribblejrClassExt._forceNative(101352, -2147483648) not set before reading it`

It looks like there's either an incomplete or removed feature here, since everywhere else the variable is called `_forceNative_UNUSED`. Removing the check for the variable works fine.

**Comment by JujuAdams** [comment]
Whoops, silly typo my end.

**Comment by JujuAdams** [comment]
a8e9e25, see also https://github.com/JujuAdams/ScribbleJunior/releases/tag/1.0.1
