### ISSUE TITLE
Crash when trying to .Draw() an element that hasn't been drawn in a couple frames

### ISSUE THREAD

**Issue by KingDevyn** [JujuAdams/ScribbleJunior#10]
I'm guessing this has to do with the integrated garbage collector for Scribblejr. I had some clauses that would make it so various elements including Scribblejr text elements wouldn't be drawn if I knew another layer was going to be drawn over it. It was easy enough to remove those checks and just execute all draws regardless, but it was confusing for awhile why this was the case. Maybe this just goes on an FAQ or something if there's not a more gracious way to handle this error without refactoring too much. Anyway, I thought I'd report it. Error report below. No additional outputs given from Scribblejr besides init message.

```
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object o_control:

vertex_submit argument 1 incorrect type (undefined) expecting a vertex buffer
 at gml_Script___DrawVertexBuffer@anon@4418@__ScribblejrClass___ScribblejrClass (line 169) -         vertex_submit(__vertexBuffer, pr_trianglelist, __fontTexture);
############################################################################################
gml_Script___DrawVertexBuffer@anon@4418@__ScribblejrClass___ScribblejrClass (line 169)
gml_Script_Draw@anon@137@__ScribblejrClassWrapper___ScribblejrClassWrapper (line 9) -         __element.Draw(_x, _y, _colour, _alpha, _sdfEffects);
gml_Script_sc_draw_set_box_array (line 204) -                             _element.Draw(_text_x,_text_y,pal_true_black,.125)
gml_Script_sc_draw_menu_fonts (line 3) - sc_draw_set_box_array(menu_in,true)
gml_Object_o_control_Draw_73 (line 303) -        lut_menu_to_draw[_menu_in]()
```

**Comment by JujuAdams** [comment]
Strange ... not run into this in my usage yet. Is it possible to replicate this in an isolated project or is it particular to your project?

**Comment by KingDevyn** [comment]
I was able to replicate in an isolated project with just Scribble Jr, and the following code in a controller object placed in the first room:

create event:
`element = Scribblejr("Press <Space> to toggle .Draw()");
show_text = true`
step event:
`if keyboard_check_pressed(vk_space){
	show_text = !show_text
	}`
draw event:
`if show_text{
	element.Draw(0,0)
	}`

Notably, if you toggle show_text off for less than ~1 second, it won't trigger the error.

**Comment by JujuAdams** [comment]
Ok! Good work.

**Comment by JujuAdams** [comment]
Was a silly mistake on my behalf: https://github.com/JujuAdams/ScribbleJunior/commit/8d6d3b1c3f69bb0daa46de188f19ce29a33fe707
