### ISSUE TITLE
ScribbleJr text coloring not really working

### ISSUE THREAD

**Issue by abbydomi** [JujuAdams/ScribbleJunior#11]
I'm unsure if I'm setting up something wrong myself which I assume I'm doing, I couldn't find help in the docs or online for my specific issue :(

I'm setting up the colors like so at the init of the game
`	ScribblejrSetDefaultFont(m5x7)
	ScribblejrAddColor("c_red", c_red)
	ScribblejrAddColor("c_blue", c_blue)`

after this I'm drawing a string like this 
`var scrbb = Scribblejr("This text is [c_red]red[/c] and this text is [c_blue]blue[/c].", fa_left, fa_top, m5x7, 1)
scrbb.Draw(x, y)`

And this is the result :(

<img width="1392" alt="Screenshot 2024-07-12 at 18 42 16" src="https://github.com/user-attachments/assets/5713f144-0213-4bab-a5ab-bdf7001cb735">

Am I doing something wrong?? Why is the text still white?

**Comment by abbydomi** [comment]
My bad! ScribbleJr function won't register the color, ScribbleJrExt is the one to use!

**Comment by JujuAdams** [comment]
Glad you figured it out. Good luck with your game.
