### ISSUE TITLE
ScribblejrFitExt - color codes eat successive spaces

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/ScribbleJunior#8]
it doesn't seem to happen with normal ScribblejrExt, which makes me think it's something to do with the text wrapping

![image](https://github.com/JujuAdams/ScribbleJunior/assets/7087495/eb4bce94-9405-475d-92f9-1c523986a90d)

[scribble jr fit ext color codes eat successive spaces.zip](https://github.com/JujuAdams/ScribbleJunior/files/14622293/scribble.jr.fit.ext.color.codes.eat.successive.spaces.zip)

**Comment by JujuAdams** [comment]
Each function has its own parser/layout system so there's no shared code (at least in that bit). I seem to recall ignoring empty strings in that particular parser and I suspect this issue is downstream of that.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/ScribbleJunior/commit/fc5600f588db6c3759d79aaf6ac9f3729121b45b
