### ISSUE TITLE
ScribblejrDrawNative function misname/manual mismatch

### ISSUE THREAD

**Issue by KingDevyn** [JujuAdams/ScribbleJunior#9]
The script resource "**ScribblejrDrawNative**" names the function inside as **ScribblejrNative()** at line 21. 

My suggestion is to rename the function from **ScribblejrNative()** to **ScribblejrDrawNative()** to match the naming conventions of other script assets & functions, and to match the documentation.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/ScribbleJunior/commit/b9005b229fed4bc0aca920f954fe05a044795d92
